<?php

namespace AppBundle\Repository;

/**
 * SubQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
