<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\Session\Session;
use AppBundle\Entity\Answer;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
    public function findAnswerByExerciceAndUser($exerciceId)
    {
        $session = new Session();
        $utilisateurId = $session->get("id");
        
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select("a")
            ->from($this->_entityName, "a")
            ->leftJoin("a.question", "q")
            ->where("a.utilisateur = :utilisateur")
                ->setParameter("utilisateur", $utilisateurId)
            ->andWhere("q.exercice = :exercice")
                ->setParameter("exercice", $exerciceId)
            ->orderBy("a.id")
        ;
        
        $query = $queryBuilder->getQuery();
        $resultat = $query->getResult();
        
        return $resultat;
    }
    
    public function findAnswerOrNot($id)
    {
        $resultat = $this->findAnswerByExerciceAndUser($id);
        $iteration = 0;
        
        foreach($resultat as $resultatBoucle)
        {
            $iteration++;
        }
        
        return $iteration > 0;
    }
    
    public function findAndDeleteAnswer(){
        $queryBuilder = $this->_em->createQueryBuilder()
            ->delete(Answer::class, "a")
            ->where('a.dateCreation < :dateSupression')
                ->setParameter(':dateSupression', new \DateTime("-6 hours"))
        ;
        
        $queryBuilder->getQuery()->execute();
        
    }
}
