<?php

namespace AppBundle\Entity;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findChapitresOrderByMatiere()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select("c")
            ->from($this->_entityName, "c")
            ->leftJoin("c.matiere", "m")
            ->orderBy("m.ordre")
        ;

        $query = $queryBuilder->getQuery();
        $resultat = $query->getResult();

        return $resultat;
    }
}
