<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassroomRepository extends EntityRepository
{
    
    public function findClassesPourExercicesPrioritaires()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select("c")
            ->from($this->_entityName, "c")
            ->leftJoin("c.exercices", "e")
            ->where('e.id IS NOT NULL')
            ->addOrderBy("c.id", "ASC")
        ;

        return $queryBuilder->getQuery()->getResult();
        
    }
}