<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoodAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodAnswerRepository extends EntityRepository
{
    public function getPropositionsByQuestion($question)
    {
        $GoodAnswer = $this
            ->createQueryBuilder('g')
            ->leftJoin("g.question", "question")
            ->where('question.id = :id')
            ->setParameter('id', $question)
        ;
        
        return $GoodAnswer;
    }
}
