<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoodAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeQuestionRepository extends EntityRepository
{
    
}
